version: '3'

services:
  postgres:
    mem_limit: 512m
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env

  postgres_admin:
    mem_limit: 512m
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '15432:80'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  # api-gateway:
  #   mem_limit: 1024m
  #   build:
  #     context: ./
  #     dockerfile: ./apps/api-gateway/Dockerfile
  #     target: development
  #   ports:
  #     - '3001:3001'
  #   env_file:
  #     - ./apps/api-gateway/.env
  #   depends_on:
  #     - auth
  #     - postgres
  #     - rabbitmq
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: npm run start:dev api-gateway && npx prisma migrate dev

  # auth:
  #   mem_limit: 512m
  #   build:
  #     context: ./
  #     dockerfile: ./apps/auth/Dockerfile
  #     target: development
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #     - rabbitmq
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: npm run start:dev auth && npx prisma migrate dev

  # meals:
  #   mem_limit: 512m
  #   build:
  #     context: ./
  #     dockerfile: ./apps/meals/Dockerfile
  #     target: development
  #   env_file:
  #     - .env
  #   depends_on:
  #     - auth
  #     - postgres
  #     - rabbitmq
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: npm run start:dev meals && npx prisma migrate dev
