apiVersion: apps/v1
kind: Deployment
metadata:
  name: workouts-deployment
  labels:
    app: workouts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workouts
  template:
    metadata:
      labels:
        app: workouts
    spec:
      containers:
      - name: workouts
        image: workouts:latest
---
apiVersion: v1
kind: Service
metadata:
  name: workouts-service
spec:
  selector:
    app: workouts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
